spring:
  application:
    name: ms-product
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: configserver:http://localhost:8888
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 9999